master-c27-gc5aa3d0-b160

diff --git a/autorsync b/autorsync
--- a/autorsync
+++ b/autorsync
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
 set -euo pipefail
 shopt -u failglob
-shopt -s lastpipe #inherit_errexit
+shopt -s lastpipe huponexit #inherit_errexit
 DEBUG={DEBUG:-1}
 
-VERSION=master-c26-ge7e296e-b148
-NPM_VERSION=1.26.148
+VERSION=master-c27-gc5aa3d0-b160
+NPM_VERSION=1.27.160
 
 ## KNOWN ISSUES
 ## * fswatch on MacOS does not detect deleted folder (CHECK)
@@ -22,6 +22,9 @@ NPM_VERSION=1.26.148
 ## * --install and --install-symlink as they are in git-rev-label
 ## * Useful hack -- protect myself from writing while executing
 ## * Implement options under construction!
+## * For two side sync it is required to distinguish updates made by autorsync and updates made by others. To suppress cyclic updates.
+## * OPTIMIZATION if DST is ssh-url, start rsyncd on destination host and user rsync:// for often rsync requests. Will be faster because does not need to open ssh connection every time.
+## * OPTIMIZATION Consider locate .rsync-temp in RAM, at least low low size files.
 
 function darwin_aliases {
    if test `uname` == Darwin ;then
@@ -123,7 +126,7 @@ fi
 function echoerr  { >/dev/stderr echo $'\e[0;31m'"ERR  $@"$'\e[0m'; }
 function fatalerr { 
    echoerr "$@"
-   stacktrace2 2
+   stacktrace    #2 2
    exit 1
 }
 alias die=fatalerr
@@ -172,11 +175,14 @@ contains_element(){
    return 1
 }
 
-# for_each(){
-#    for elem in ${!1[@]} ;do
-#       eval "$@" $testname
-#    done
-# }
+## Usage for_each var_name in array_name do 
+for_each_in_var(){
+   declare -rn _a=$1
+   shift
+   for elem in ${!_a[@]} ;do
+      eval "$@" $elem
+   done
+}
 
 kill_sure(){
    kill -TERM "$@" &>/dev/null ||  return 0   ## Already dead
@@ -187,13 +193,17 @@ kill_sure(){
    fi
 }
 
-#function OnError {  caller | { read line file; echoerr "in $file:$line" >&2; };  }
-OnError(){ stacktrace; }
+function OnError {  caller | { read line file; echoerr "in $file:$line"; };  }
+#OnError(){ echoerr "in $BASH_SOURCE:$BASH_LINENO"; stacktrace; }
+#OnError(){ echoerr "in ${BASH_SOURCE[1]}:${BASH_LINENO[0]}"; stacktrace; }
 trap OnError ERR
 ### END utils.bash ###
 
 
-trap_append 'jobs; ps=$(jobs -p); ${ps:+ kill $ps} || true; jobs' INT HUP EXIT
+trap_append 'echoinfo autorsync: TERMINATED' TERM
+trap_append 'echoinfo autorsync: INTERRUPTED' INT
+trap_append 'echoinfo autorsync: CAUGHT SIGHUP' HUP
+trap_append 'ps=$(jobs -p); ${ps:+ kill $ps} || true;' EXIT
 #trap "kill -hup 0" hup
 
 unset SRC
@@ -217,7 +227,7 @@ do
          exit
          ;;
       --period=*)
-         period="${1##--period=}"
+         period="${1#--period=}"
          ;;
       --exclude=*)
          echo "$1" >>$EXCLUDES_LIST
@@ -243,6 +253,10 @@ do
          ;;
       --initial-tx|--enable-initial-tx|--use-initial-tx)
          USE_INITIAL_TX=y
+         ;;
+      --initial-tx-only)
+         USE_INITIAL_TX=y
+         unset USE_TX USE_RX
          ;;
       --initial-tx-delete-missing)
          echowarn "Option --initial-tx-delete-missing is under construction!"
@@ -320,7 +334,7 @@ do
 done
 ## Assert
 var_is_set_not_empty SRC || fatalerr "Source is not set" 
-var_is_set_not_empty DST || fatalerr "Destionation is not set" 
+var_is_set_not_empty DST || fatalerr "Destination is not set" 
 ## If SRC ends with slash '/' sync folder contents without the folder itself
 ## ToDo: consider combinations DST/SRC/file/directory
 
@@ -375,17 +389,17 @@ function initial_tx
    fi
    #mkdir -p .rsync.temp  #mktemp -d 
    $SSH $DST_HOST mkdir -p "$DST_PATH"/.rsync.temp #bash -xc "test -d '$DST_PATH' && mkdir -p '$DST_PATH'/.rsync.temp || mkdir -p '$DST_PATH'.rsync.temp"
-   rsync --archive --relative --info=progress2  \
+   if rsync --archive --info=progress2  \
          --temp-dir=.rsync.temp  \
          --exclude-from=$EXCLUDES_LIST \
          ${RSYNC_PATH:+"--rsync-path=$RSYNC_PATH"} \
          ${RSH:+"--rsh=$RSH"} \
          "$SRC" "$DST" \
-         ${FIND_FILES:+ --files-from=<(find "$SRC" | sed -E 's#'"$SRC"'/?##g')}  &&
-      echoinfo "Initial sync to container done."  ||
-      echowarn "Initial sync finished with errors/warnings."
-         #"$SRC" "$DST_HOST:$DST_PATH" \
-         #--temp-dir=.rsync.temp \
+         #${FIND_FILES:+ --files-from=<(find "$SRC" | sed -E 's#'"$SRC"'/?##g')}
+         #--relative 
+   then echoinfo "Initial sync to container done."
+   else echowarn "Initial sync finished with errors/warnings."
+   fi
 }
 
 function fswatch_cmd
@@ -413,44 +427,50 @@ function normalize_path
 
 function rsync_cmd
 {
-   ## ToDo OPTIMIZATION if DST is ssh-url, start rsyncd on destination host and user rsync:// for often rsync requests. Will be faster because does not need open ssh connection every time.
+   ## ToDo OPTIMIZATION if DST is ssh-url, start rsyncd on destination host and user rsync:// for often rsync requests. Will be faster because does not need to open ssh connection every time.
    ff=$(mktemp) && 
       trap_append "echodbg 'Clean up rsync_cmd. Removing ff $ff'; rm $ff" EXIT
    while read -d $'\x04' ;do
-      echodbg "$(test "$1" == "$SRC" && echo "L==>R" || echo "L<==R") $REPLY"
-      echo "$REPLY" >$ff #| cut -d' ' -f1 >$ff
+      echodbg "$(test "$src" == "$SRC" && echo "-->" || echo "<--") " #$REPLY"
+      echo "$REPLY" >$ff
       normalize_path "$NORMALIZE_PATH" -i $ff
-      echodbg ============ "RSYNC_PATH=$RSYNC_PATH"
-      rsync --archive --relative --delete --delete-missing-args  \
+      if rsync --archive --relative --delete --delete-missing-args  \
             --info=progress2 --files-from=$ff  \
             --temp-dir=.rsync.temp --exclude='.rsync.temp/*' \
+            "$src" "$dst" \
             ${RSYNC_PATH:+"--rsync-path=$RSYNC_PATH"} \
             ${RSH:+"--rsh=$RSH"} \
-            "$@"  \
-         || echowarn "Failed to sync: $(cat $ff)"
+            "$@" \
+            #${FIND_FILES:+ --files-from=<(find "$1" | sed -E 's#'"$1"'/?##g')}
+      then :
+      else echowarn "Failed to sync: $(cat $ff)"
+      fi
    done
 }
 
 function rsync_tx
 {
-   test -d $SRC &&
-      local dir="$SRC/.rsync.temp"  ||
-      local dir="${SRC%/*}/.rsync.temp"
-   mkdir -p "$dir"
-   trap_append "echodbg 'Cleanup rsync_tx. Removing \"$dir\"'; rm -rf \"$dir\"" EXIT
-
    $SSH $DST_HOST mkdir -p "$DST_PATH"/.rsync.temp
    trap_append "echodbg 'Cleanup rsync_tx. Removing ssh://\"$DST_PATH/.rsync.temp\"'; $SSH $DST_HOST rm -rf \"$DST_PATH/.rsync.temp\"" EXIT
-
+ 
    NORMALIZE_PATH="$(realpath "$SRC")"
    echodbg NORMALIZE_PATH $NORMALIZE_PATH
+   
    fswatch_cmd "$SRC" | 
       NORMALIZE_PATH="$(realpath "$SRC")" \
-      rsync_cmd "$SRC" "$DST"
+      src="$SRC" dst="$DST" rsync_cmd
 }
 
 function rsync_rx
 {
+   ## ToDo Create rsync.temp on local side
+   # if test -d $SRC
+   # then local tempdir="$SRC/.rsync.temp"
+   # else local tempdir="${SRC%/*}/.rsync.temp"
+   # fi
+   # mkdir -p "$tempdir"
+   # trap_append "echodbg 'Cleanup rsync_tx. Removing \"$tempdir\"'; rm -rf \"$tempdir\"" EXIT
+
    remote_command() {
       set -euo pipefail
       trap OnError ERR
@@ -459,7 +479,7 @@ function rsync_rx
       ulimit -n 10000
       fswatch_cmd "$DST_PATH"
    }
-   $SSH $DST_HOST ${REMOTE_PATH:+$REMOTE_PATH/}bash -<<END  | NORMALIZE_PATH="$($SSH "$DST_HOST" ${REMOTE_PATH:+$REMOTE_PATH/}realpath "$DST_PATH")" rsync_cmd "$DST" "$SRC"
+   $SSH $DST_HOST ${REMOTE_PATH:+$REMOTE_PATH/}bash -<<END  | NORMALIZE_PATH="$($SSH "$DST_HOST" ${REMOTE_PATH:+$REMOTE_PATH/}realpath "$DST_PATH")" src="$DST" dst="$SRC" rsync_cmd
       set -euo pipefail
       if test `uname` == Darwin ;then export PATH="/usr/local/bin:$PATH" ;fi
       $(cat $mydir/utils.bash)
@@ -472,22 +492,28 @@ END
    unset -f remote_command
 }
 
-## Sync on change
-test $(uname -s) == Darwin && period=0.5 || period=1
-#echoinfo "Startning sync_on_change with period=$period"
 
-DST_HOST=$(cut -d: -f1 <<<$DST)
-DST_PATH=$(cut -d: -f2 <<<$DST)
+DST_HOST="${DST%:*}"  #$(cut -d: -f1 <<<$DST)
+DST_PATH="${DST#*:}"  #$(cut -d: -f2 <<<$DST)
 REMOTE_UNAME="$($SSH $DST_HOST uname)"
 var_is_unset_or_empty REMOTE_PATH && test $REMOTE_UNAME = Darwin && REMOTE_PATH=/usr/local/bin
 var_is_unset_or_empty RSYNC_PATH  && test $REMOTE_UNAME = Darwin && RSYNC_PATH="${REMOTE_PATH:+$REMOTE_PATH/}rsync"
+if var_is_set_not_empty USE_TX && var_is_set_not_empty USE_RX
+then fatalerr "Two side sync is not stable!" ;fi
+#test $(uname -s) == Darwin && period=0.5 || period=1
+
+if var_is_set USE_INITIAL_TX ;then
+   echoinfo "Begin initial_tx"
+   initial_tx
+   echoinfo "Done initial_tx"
+fi
+
+if ! test "${SRC: -1}" = /  || ! test -d "$SRC"
+then  DST+="/`basename "$SRC"`/"
+      DST_PATH="${DST#*:}"
+fi
 
 if var_is_set_not_empty USE_TX ;then
-   if var_is_set USE_INITIAL_TX ;then
-      echoinfo "Begin initial_tx"
-      initial_tx
-      echoinfo "Done initial_tx"
-   fi
    echoinfo "Starting rsync_tx"
    rsync_tx  & pid_tx=$!
    sleep 0.2 && kill -0 $pid_tx 2>&- ||  fatalerr "rsync_tx $pid_tx failed to start"  ## Check process is running successfully
